### PR TITLE
add copy to clipboard feature

### PR DESCRIPTION
**Pull request by xiwc**
image

image

### CODE REVIEW

**Comment by listepo** [comment]
+1

**Comment by zenorocha** [comment]
+1 ;)

**Comment by zenorocha** [comment]
btw, Bootstrap 4 is now using clipboard.js too!

**Comment by jlukic** [comment]
This has been implemented.

**Comment by stubbystudios** [comment]
I cannot figure out how it has been implemented. I can get text to copy from input fields, but not from <code>

**Pull request closed without merging**
