### PR TITLE
Add search input and keyboard shortcuts

### PR DESCRIPTION
**Pull request by pcj**
* Replaces the fixed-menu `<div class="title item">` with `<div class="search item">` that contains a `search input item`.  The html.eco file statically initializes the placeholder to the document.title.  This is a little sneaky as it is not obvious that this element is a search input, but maintains the appearance of the existing UI without sacrificing real estate in the fixed menu bar; this could be changed to a dedicated separate item in the menu if desired.
* Adds an event listener to `$('search')` input element to initialize the search functionality the first time a user focuses the search input.
* Search input source initialization will `$.getJSON('src/metadata.json')`, which is generated by the `gulp build-docs` command.
* Adds keyboard shortcuts `s` (focus the search input) and `?` (show a small modal describing the shortcuts) and adds dependency on `jquery.hotkeys.js`.

### CODE REVIEW

**Comment by jlukic** [comment]
Checkin

**Comment by jlukic** [comment]
Redoing the ui a little bit, but keeping the same. in general

**Comment by jlukic** [comment]
Forgot to tag some commits bb8bdc7bdb913b838a4b26e2c97ea8bed9f88d48 726a6c485b55445ecb4c1582f7e704cf7b8187d1 2df8bd81c5786899545a9717af65ac4bdaf60c99

**Comment by jlukic** [comment]
Keyboard shortcuts appear to be borked, related to https://github.com/tzuryby/jquery.hotkeys/issues/45

**Comment by pcj** [comment]
I am seeing this only on the welcome page (index.html); not able to reproduce with any other page.  Are you seeing same?

**Comment by jlukic** [comment]
Yeah. I also notice swapping to `on` from `bind` breaks it

**Comment by jlukic** [comment]
I'm slightly redoing the look & feel of docs for `2.0` to use a fixed sidebar so will need to move around search as well
img

**Comment by pcj** [comment]
I'm working on this...  From results so far I think there is a bug in
jquery.hotkeys...

it may be that it seems to operate under the assumption that it is the only
one using jquery special events.  If other scripts are using it, it may
break.

Will have to look into if there is something about the semantic docs ui
welcome page that registers something under special events before hotkeys.

**Comment by jlukic** [comment]
I think using a different library is probably ideal. That ones pretty old

**Comment by pcj** [comment]
That's probably a good call.  I was just looking at Mousetrap myself.  You want me to make the change? 

Also, if you do to a fixed left sidebar layout, you may not need the search function at all.  But it does show off the feature nicely.

**Comment by jlukic** [comment]
Is it ok if I ping you in a couple days. I want to get all the moving parts of the design out of the way before asking for a PR.

**Comment by pcj** [comment]
yep

**Pull request merged**
