### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by bahmani00**
splace  should be 'a place'

### CODE REVIEW

**Comment by lubber-de** [comment]
Nice catch! Would you like to submit the same change to the active community fork [Fomantic-UI](https://fomantic-ui.com) as well?
https://github.com/fomantic/Fomantic-UI-Docs

**Comment by bahmani00** [comment]
> Nice catch! Would you like to submit the same change to the active community fork [Fomantic-UI](https://fomantic-ui.com) as well?
> https://github.com/fomantic/Fomantic-UI-Docs

Done: [PR: #261](https://github.com/fomantic/Fomantic-UI-Docs/pull/261)
You may review and approve to merge

**Comment by lubber-de** [comment]
> You may review and approve to merge

Done and merged :) Thanks

**Comment by bahmani00** [comment]
> > You may review and approve to merge
> 
> Done and merged :) Thanks

My pleasure, thanks

**Comment by bahmani00** [comment]
> > You may review and approve to merge
> 
> Done and merged :) Thanks

Should I close this PR?

**Comment by lubber-de** [comment]
> Should I close this PR?
No, it's still valid for this repo

**Pull request closed without merging**
