### PR TITLE
Update input.html.eco

### PR DESCRIPTION
**Pull request by avalanche1**
this way it shows what 'inverted' means

### CODE REVIEW

**Comment by jlukic** [comment]
Looks like you have a typo.

**Comment by avalanche1** [comment]
my bad

**Comment by avalanche1** [comment]
I'd change HTML snippet as well but don't know where it is in docs repo

**Comment by jlukic** [comment]
https://github.com/Semantic-Org/Semantic-UI-Docs/tree/master/server/partials/examples

**Pull request merged**
