### PR TITLE
Added Font Awesome 4.7.0 icons

### PR DESCRIPTION
**Pull request by Banandrew**
Resolves Semantic-Org/Semantic-UI#5158.

### CODE REVIEW

**Comment by peyman-mohamadpour** [comment]
Thank you for this PR, it clearly added couple of previously missing icons to the documentation. Although some other useful are still missing:

address book
address card
bath
shower
drivers licsence
handshake
id-card
telegram
thermometer

Thanks

**Comment by Banandrew** [comment]
@peyman-mohamadpour All of the 4.7’s icons were added, I just skipped aliases; for example, `drivers-license` is an alias of `id-card`, and so on.

**Comment by peyman-mohamadpour** [comment]
Please take a look at [this url](https://semantic-ui.com/elements/icon.html)

**Comment by jlukic** [comment]
5.0

**Pull request closed without merging**
