### PR TITLE
Slider docs

### PR DESCRIPTION
**Pull request by gdaunton**
These are the docs for my slider pr.

This depends on https://github.com/Semantic-Org/Semantic-UI/pull/4910

/cc @jlukic @flytreeleft

### CODE REVIEW

**Comment by flytreeleft** [comment]
Waiting for merging slider to master :)

**Comment by jlukic** [comment]
@gdaunton I know you've been in limbo. I am hoping to look through this and give some feedback sometime soon

**Comment by gdaunton** [comment]
@jlukic Hey! Any update on this?

**Comment by Melmoth-the-Wanderer** [comment]
I'm actually using this in production. Would be nice to merge it into the 'core'. Thanks for the PR!

**Pull request closed without merging**
