### PR TITLE
Changed icons page for FontAwesome 5 port

### PR DESCRIPTION
**Pull request by hammy2899**
Changes the icons page to complete the FontAwesome 5 port. 

I have commented out some code in the `docs.css` file to fix the new code icons

Here is the PR for the FontAwesome port https://github.com/Semantic-Org/Semantic-UI/pull/6085/

### CODE REVIEW

**Comment by jlukic** [comment]
@hammy2899 it looks like quite a few icons are placed in multiple categories. 

I'm going to try my best to dedupe them.

I'm also adding icon search to make it easier to use.

**Comment by hammy2899** [comment]
@jlukic Ye I was debating whether to add duplicate icons because FA5 docs has them in multiple categories but do whatever you feel is best.

**Comment by jlukic** [comment]
I'm going to go ahead and leave the duplicates in docs, I think it makes sense to remove them from the overrides file as they will appear as duplicate css rules in the compiled css.

**Comment by hammy2899** [comment]
Ye I totally agree 👍

**Comment by jlukic** [comment]
I've merged this in from `https://github.com/Semantic-Org/Semantic-UI-Docs/tree/hammy2899-fa5

**Pull request closed without merging**
